// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("windowseventtrace")
	ScopeName = "github.com/dynatrace/dynatrace-bindplane-otel-contrib/receiver/windowseventtracereceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
