// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["traceroute.hop.latency"] = mb.metricTracerouteHopLatency.config.AggregationStrategy
			aggMap["traceroute.hop.status"] = mb.metricTracerouteHopStatus.config.AggregationStrategy
			aggMap["traceroute.hops"] = mb.metricTracerouteHops.config.AggregationStrategy
			aggMap["traceroute.reached"] = mb.metricTracerouteReached.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordTracerouteHopLatencyDataPoint(ts, 1, 20, "traceroute.hop.address-val", AttributeTracerouteTriggerScheduled, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordTracerouteHopLatencyDataPoint(ts, 3, 21, "traceroute.hop.address-val-2", AttributeTracerouteTriggerPingFailure, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordTracerouteHopStatusDataPoint(ts, 1, 20, "traceroute.hop.address-val", AttributeTracerouteTriggerScheduled, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordTracerouteHopStatusDataPoint(ts, 3, 21, "traceroute.hop.address-val-2", AttributeTracerouteTriggerPingFailure, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordTracerouteHopsDataPoint(ts, 1, AttributeTracerouteTriggerScheduled, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordTracerouteHopsDataPoint(ts, 3, AttributeTracerouteTriggerPingFailure, "dns.server-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordTracerouteReachedDataPoint(ts, 1, AttributeTracerouteTriggerScheduled, "dns.server-val")
			if tt.name == "reaggregate_set" {
				mb.RecordTracerouteReachedDataPoint(ts, 3, AttributeTracerouteTriggerPingFailure, "dns.server-val-2")
			}

			rb := mb.NewResourceBuilder()
			rb.SetServerAddress("server.address-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricTracerouteHopLatency.aggDataPoints)
				assert.Empty(t, mb.metricTracerouteHopStatus.aggDataPoints)
				assert.Empty(t, mb.metricTracerouteHops.aggDataPoints)
				assert.Empty(t, mb.metricTracerouteReached.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "traceroute.hop.latency":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["traceroute.hop.latency"], "Found a duplicate in the metrics slice: traceroute.hop.latency")
						validatedMetrics["traceroute.hop.latency"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Round-trip time to a hop that answered. Not emitted for hops that did not answer.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						tracerouteHopIndexAttrVal, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.True(t, ok)
						assert.EqualValues(t, 20, tracerouteHopIndexAttrVal.Int())
						tracerouteHopAddressAttrVal, ok := dp.Attributes().Get("traceroute.hop.address")
						assert.True(t, ok)
						assert.Equal(t, "traceroute.hop.address-val", tracerouteHopAddressAttrVal.Str())
						tracerouteTriggerAttrVal, ok := dp.Attributes().Get("traceroute.trigger")
						assert.True(t, ok)
						assert.Equal(t, "scheduled", tracerouteTriggerAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["traceroute.hop.latency"], "Found a duplicate in the metrics slice: traceroute.hop.latency")
						validatedMetrics["traceroute.hop.latency"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Round-trip time to a hop that answered. Not emitted for hops that did not answer.", mi.Description())
						assert.Equal(t, "ms", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["traceroute.hop.latency"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("traceroute.hop.address")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("traceroute.trigger")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "traceroute.hop.status":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["traceroute.hop.status"], "Found a duplicate in the metrics slice: traceroute.hop.status")
						validatedMetrics["traceroute.hop.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the hop answered one of its probes, 0 if it answered none. Averaged over time, the fraction of traces in which the hop answered.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						tracerouteHopIndexAttrVal, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.True(t, ok)
						assert.EqualValues(t, 20, tracerouteHopIndexAttrVal.Int())
						tracerouteHopAddressAttrVal, ok := dp.Attributes().Get("traceroute.hop.address")
						assert.True(t, ok)
						assert.Equal(t, "traceroute.hop.address-val", tracerouteHopAddressAttrVal.Str())
						tracerouteTriggerAttrVal, ok := dp.Attributes().Get("traceroute.trigger")
						assert.True(t, ok)
						assert.Equal(t, "scheduled", tracerouteTriggerAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["traceroute.hop.status"], "Found a duplicate in the metrics slice: traceroute.hop.status")
						validatedMetrics["traceroute.hop.status"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the hop answered one of its probes, 0 if it answered none. Averaged over time, the fraction of traces in which the hop answered.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["traceroute.hop.status"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("traceroute.hop.index")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("traceroute.hop.address")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("traceroute.trigger")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "traceroute.hops":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["traceroute.hops"], "Found a duplicate in the metrics slice: traceroute.hops")
						validatedMetrics["traceroute.hops"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of hops the trace probed. 0 when the trace could not run.", mi.Description())
						assert.Equal(t, "{hop}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						tracerouteTriggerAttrVal, ok := dp.Attributes().Get("traceroute.trigger")
						assert.True(t, ok)
						assert.Equal(t, "scheduled", tracerouteTriggerAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["traceroute.hops"], "Found a duplicate in the metrics slice: traceroute.hops")
						validatedMetrics["traceroute.hops"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of hops the trace probed. 0 when the trace could not run.", mi.Description())
						assert.Equal(t, "{hop}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["traceroute.hops"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("traceroute.trigger")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				case "traceroute.reached":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["traceroute.reached"], "Found a duplicate in the metrics slice: traceroute.reached")
						validatedMetrics["traceroute.reached"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the destination answered, 0 if it did not or the trace could not run.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						tracerouteTriggerAttrVal, ok := dp.Attributes().Get("traceroute.trigger")
						assert.True(t, ok)
						assert.Equal(t, "scheduled", tracerouteTriggerAttrVal.Str())
						dnsServerAttrVal, ok := dp.Attributes().Get("dns.server")
						assert.True(t, ok)
						assert.Equal(t, "dns.server-val", dnsServerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["traceroute.reached"], "Found a duplicate in the metrics slice: traceroute.reached")
						validatedMetrics["traceroute.reached"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "1 if the destination answered, 0 if it did not or the trace could not run.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["traceroute.reached"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("traceroute.trigger")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("dns.server")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
