// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"slices"
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeTracerouteTrigger specifies the value traceroute.trigger attribute.
type AttributeTracerouteTrigger int

const (
	_ AttributeTracerouteTrigger = iota
	AttributeTracerouteTriggerScheduled
	AttributeTracerouteTriggerPingFailure
)

// String returns the string representation of the AttributeTracerouteTrigger.
func (av AttributeTracerouteTrigger) String() string {
	switch av {
	case AttributeTracerouteTriggerScheduled:
		return "scheduled"
	case AttributeTracerouteTriggerPingFailure:
		return "ping_failure"
	}
	return ""
}

// MapAttributeTracerouteTrigger is a helper map of string to AttributeTracerouteTrigger attribute value.
var MapAttributeTracerouteTrigger = map[string]AttributeTracerouteTrigger{
	"scheduled":    AttributeTracerouteTriggerScheduled,
	"ping_failure": AttributeTracerouteTriggerPingFailure,
}

var MetricsInfo = metricsInfo{
	TracerouteHopLatency: metricInfo{
		Name:       "traceroute.hop.latency",
		Attributes: []string{"traceroute.hop.index", "traceroute.hop.address", "traceroute.trigger", "dns.server"},
	},
	TracerouteHopStatus: metricInfo{
		Name:       "traceroute.hop.status",
		Attributes: []string{"traceroute.hop.index", "traceroute.hop.address", "traceroute.trigger", "dns.server"},
	},
	TracerouteHops: metricInfo{
		Name:       "traceroute.hops",
		Attributes: []string{"traceroute.trigger", "dns.server"},
	},
	TracerouteReached: metricInfo{
		Name:       "traceroute.reached",
		Attributes: []string{"traceroute.trigger", "dns.server"},
	},
}

type metricsInfo struct {
	TracerouteHopLatency metricInfo
	TracerouteHopStatus  metricInfo
	TracerouteHops       metricInfo
	TracerouteReached    metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricTracerouteHopLatency struct {
	data          pmetric.Metric                   // data buffer for generated metric.
	config        TracerouteHopLatencyMetricConfig // metric config provided by user.
	capacity      int                              // max observed number of data points added to the metric.
	aggDataPoints []float64                        // slice containing number of aggregated datapoints at each index
}

// init fills traceroute.hop.latency metric with initial data.
func (m *metricTracerouteHopLatency) init() {
	m.data.SetName("traceroute.hop.latency")
	m.data.SetDescription("Round-trip time to a hop that answered. Not emitted for hops that did not answer.")
	m.data.SetUnit("ms")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricTracerouteHopLatency) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, tracerouteTriggerAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex) {
		dp.Attributes().PutInt("traceroute.hop.index", tracerouteHopIndexAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress) {
		dp.Attributes().PutStr("traceroute.hop.address", tracerouteHopAddressAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopLatencyMetricAttributeKeyTracerouteTrigger) {
		dp.Attributes().PutStr("traceroute.trigger", tracerouteTriggerAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopLatencyMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricTracerouteHopLatency) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricTracerouteHopLatency) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricTracerouteHopLatency(cfg TracerouteHopLatencyMetricConfig) metricTracerouteHopLatency {
	m := metricTracerouteHopLatency{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricTracerouteHopStatus struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        TracerouteHopStatusMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []float64                       // slice containing number of aggregated datapoints at each index
}

// init fills traceroute.hop.status metric with initial data.
func (m *metricTracerouteHopStatus) init() {
	m.data.SetName("traceroute.hop.status")
	m.data.SetDescription("1 if the hop answered one of its probes, 0 if it answered none. Averaged over time, the fraction of traces in which the hop answered.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricTracerouteHopStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, tracerouteTriggerAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopStatusMetricAttributeKeyTracerouteHopIndex) {
		dp.Attributes().PutInt("traceroute.hop.index", tracerouteHopIndexAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopStatusMetricAttributeKeyTracerouteHopAddress) {
		dp.Attributes().PutStr("traceroute.hop.address", tracerouteHopAddressAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopStatusMetricAttributeKeyTracerouteTrigger) {
		dp.Attributes().PutStr("traceroute.trigger", tracerouteTriggerAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopStatusMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricTracerouteHopStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricTracerouteHopStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricTracerouteHopStatus(cfg TracerouteHopStatusMetricConfig) metricTracerouteHopStatus {
	m := metricTracerouteHopStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricTracerouteHops struct {
	data          pmetric.Metric             // data buffer for generated metric.
	config        TracerouteHopsMetricConfig // metric config provided by user.
	capacity      int                        // max observed number of data points added to the metric.
	aggDataPoints []int64                    // slice containing number of aggregated datapoints at each index
}

// init fills traceroute.hops metric with initial data.
func (m *metricTracerouteHops) init() {
	m.data.SetName("traceroute.hops")
	m.data.SetDescription("Number of hops the trace probed. 0 when the trace could not run.")
	m.data.SetUnit("{hop}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricTracerouteHops) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, tracerouteTriggerAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopsMetricAttributeKeyTracerouteTrigger) {
		dp.Attributes().PutStr("traceroute.trigger", tracerouteTriggerAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteHopsMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricTracerouteHops) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricTracerouteHops) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricTracerouteHops(cfg TracerouteHopsMetricConfig) metricTracerouteHops {
	m := metricTracerouteHops{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricTracerouteReached struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        TracerouteReachedMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills traceroute.reached metric with initial data.
func (m *metricTracerouteReached) init() {
	m.data.SetName("traceroute.reached")
	m.data.SetDescription("1 if the destination answered, 0 if it did not or the trace could not run.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricTracerouteReached) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, tracerouteTriggerAttributeValue string, dnsServerAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, TracerouteReachedMetricAttributeKeyTracerouteTrigger) {
		dp.Attributes().PutStr("traceroute.trigger", tracerouteTriggerAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, TracerouteReachedMetricAttributeKeyDNSServer) {
		dp.Attributes().PutStr("dns.server", dnsServerAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricTracerouteReached) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricTracerouteReached) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricTracerouteReached(cfg TracerouteReachedMetricConfig) metricTracerouteReached {
	m := metricTracerouteReached{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                         MetricsBuilderConfig // config of the metrics builder.
	startTime                      pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                int                  // maximum observed number of metrics per resource.
	metricsBuffer                  pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                      component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter map[string]filter.Filter
	resourceAttributeExcludeFilter map[string]filter.Filter
	metricTracerouteHopLatency     metricTracerouteHopLatency
	metricTracerouteHopStatus      metricTracerouteHopStatus
	metricTracerouteHops           metricTracerouteHops
	metricTracerouteReached        metricTracerouteReached
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                         mbc,
		startTime:                      pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                  pmetric.NewMetrics(),
		buildInfo:                      settings.BuildInfo,
		metricTracerouteHopLatency:     newMetricTracerouteHopLatency(mbc.Metrics.TracerouteHopLatency),
		metricTracerouteHopStatus:      newMetricTracerouteHopStatus(mbc.Metrics.TracerouteHopStatus),
		metricTracerouteHops:           newMetricTracerouteHops(mbc.Metrics.TracerouteHops),
		metricTracerouteReached:        newMetricTracerouteReached(mbc.Metrics.TracerouteReached),
		resourceAttributeIncludeFilter: make(map[string]filter.Filter),
		resourceAttributeExcludeFilter: make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.ServerAddress.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["server.address"] = filter.CreateFilter(mbc.ResourceAttributes.ServerAddress.MetricsInclude)
	}
	if mbc.ResourceAttributes.ServerAddress.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["server.address"] = filter.CreateFilter(mbc.ResourceAttributes.ServerAddress.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricTracerouteHopLatency.emit(ils.Metrics())
	mb.metricTracerouteHopStatus.emit(ils.Metrics())
	mb.metricTracerouteHops.emit(ils.Metrics())
	mb.metricTracerouteReached.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordTracerouteHopLatencyDataPoint adds a data point to traceroute.hop.latency metric.
func (mb *MetricsBuilder) RecordTracerouteHopLatencyDataPoint(ts pcommon.Timestamp, val float64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, tracerouteTriggerAttributeValue AttributeTracerouteTrigger, dnsServerAttributeValue string) {
	mb.metricTracerouteHopLatency.recordDataPoint(mb.startTime, ts, val, tracerouteHopIndexAttributeValue, tracerouteHopAddressAttributeValue, tracerouteTriggerAttributeValue.String(), dnsServerAttributeValue)
}

// RecordTracerouteHopStatusDataPoint adds a data point to traceroute.hop.status metric.
func (mb *MetricsBuilder) RecordTracerouteHopStatusDataPoint(ts pcommon.Timestamp, val float64, tracerouteHopIndexAttributeValue int64, tracerouteHopAddressAttributeValue string, tracerouteTriggerAttributeValue AttributeTracerouteTrigger, dnsServerAttributeValue string) {
	mb.metricTracerouteHopStatus.recordDataPoint(mb.startTime, ts, val, tracerouteHopIndexAttributeValue, tracerouteHopAddressAttributeValue, tracerouteTriggerAttributeValue.String(), dnsServerAttributeValue)
}

// RecordTracerouteHopsDataPoint adds a data point to traceroute.hops metric.
func (mb *MetricsBuilder) RecordTracerouteHopsDataPoint(ts pcommon.Timestamp, val int64, tracerouteTriggerAttributeValue AttributeTracerouteTrigger, dnsServerAttributeValue string) {
	mb.metricTracerouteHops.recordDataPoint(mb.startTime, ts, val, tracerouteTriggerAttributeValue.String(), dnsServerAttributeValue)
}

// RecordTracerouteReachedDataPoint adds a data point to traceroute.reached metric.
func (mb *MetricsBuilder) RecordTracerouteReachedDataPoint(ts pcommon.Timestamp, val int64, tracerouteTriggerAttributeValue AttributeTracerouteTrigger, dnsServerAttributeValue string) {
	mb.metricTracerouteReached.recordDataPoint(mb.startTime, ts, val, tracerouteTriggerAttributeValue.String(), dnsServerAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
