// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// TracerouteHopLatencyMetricAttributeKey specifies the key of an attribute for the traceroute.hop.latency metric.
type TracerouteHopLatencyMetricAttributeKey string

const (
	TracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex   TracerouteHopLatencyMetricAttributeKey = "traceroute.hop.index"
	TracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress TracerouteHopLatencyMetricAttributeKey = "traceroute.hop.address"
	TracerouteHopLatencyMetricAttributeKeyTracerouteTrigger    TracerouteHopLatencyMetricAttributeKey = "traceroute.trigger"
	TracerouteHopLatencyMetricAttributeKeyDNSServer            TracerouteHopLatencyMetricAttributeKey = "dns.server"
)

// TracerouteHopLatencyMetricConfig provides config for the traceroute.hop.latency metric.
type TracerouteHopLatencyMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []TracerouteHopLatencyMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *TracerouteHopLatencyMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *TracerouteHopLatencyMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case TracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex, TracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress, TracerouteHopLatencyMetricAttributeKeyTracerouteTrigger, TracerouteHopLatencyMetricAttributeKeyDNSServer:
		default:
			return fmt.Errorf("metric traceroute.hop.latency doesn't have an attribute %v, valid attributes: [traceroute.hop.index, traceroute.hop.address, traceroute.trigger, dns.server]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// TracerouteHopStatusMetricAttributeKey specifies the key of an attribute for the traceroute.hop.status metric.
type TracerouteHopStatusMetricAttributeKey string

const (
	TracerouteHopStatusMetricAttributeKeyTracerouteHopIndex   TracerouteHopStatusMetricAttributeKey = "traceroute.hop.index"
	TracerouteHopStatusMetricAttributeKeyTracerouteHopAddress TracerouteHopStatusMetricAttributeKey = "traceroute.hop.address"
	TracerouteHopStatusMetricAttributeKeyTracerouteTrigger    TracerouteHopStatusMetricAttributeKey = "traceroute.trigger"
	TracerouteHopStatusMetricAttributeKeyDNSServer            TracerouteHopStatusMetricAttributeKey = "dns.server"
)

// TracerouteHopStatusMetricConfig provides config for the traceroute.hop.status metric.
type TracerouteHopStatusMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []TracerouteHopStatusMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *TracerouteHopStatusMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *TracerouteHopStatusMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case TracerouteHopStatusMetricAttributeKeyTracerouteHopIndex, TracerouteHopStatusMetricAttributeKeyTracerouteHopAddress, TracerouteHopStatusMetricAttributeKeyTracerouteTrigger, TracerouteHopStatusMetricAttributeKeyDNSServer:
		default:
			return fmt.Errorf("metric traceroute.hop.status doesn't have an attribute %v, valid attributes: [traceroute.hop.index, traceroute.hop.address, traceroute.trigger, dns.server]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// TracerouteHopsMetricAttributeKey specifies the key of an attribute for the traceroute.hops metric.
type TracerouteHopsMetricAttributeKey string

const (
	TracerouteHopsMetricAttributeKeyTracerouteTrigger TracerouteHopsMetricAttributeKey = "traceroute.trigger"
	TracerouteHopsMetricAttributeKeyDNSServer         TracerouteHopsMetricAttributeKey = "dns.server"
)

// TracerouteHopsMetricConfig provides config for the traceroute.hops metric.
type TracerouteHopsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                             `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []TracerouteHopsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *TracerouteHopsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *TracerouteHopsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case TracerouteHopsMetricAttributeKeyTracerouteTrigger, TracerouteHopsMetricAttributeKeyDNSServer:
		default:
			return fmt.Errorf("metric traceroute.hops doesn't have an attribute %v, valid attributes: [traceroute.trigger, dns.server]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// TracerouteReachedMetricAttributeKey specifies the key of an attribute for the traceroute.reached metric.
type TracerouteReachedMetricAttributeKey string

const (
	TracerouteReachedMetricAttributeKeyTracerouteTrigger TracerouteReachedMetricAttributeKey = "traceroute.trigger"
	TracerouteReachedMetricAttributeKeyDNSServer         TracerouteReachedMetricAttributeKey = "dns.server"
)

// TracerouteReachedMetricConfig provides config for the traceroute.reached metric.
type TracerouteReachedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []TracerouteReachedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *TracerouteReachedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *TracerouteReachedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case TracerouteReachedMetricAttributeKeyTracerouteTrigger, TracerouteReachedMetricAttributeKeyDNSServer:
		default:
			return fmt.Errorf("metric traceroute.reached doesn't have an attribute %v, valid attributes: [traceroute.trigger, dns.server]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for networkcheck metrics.
type MetricsConfig struct {
	TracerouteHopLatency TracerouteHopLatencyMetricConfig `mapstructure:"traceroute.hop.latency"`
	TracerouteHopStatus  TracerouteHopStatusMetricConfig  `mapstructure:"traceroute.hop.status"`
	TracerouteHops       TracerouteHopsMetricConfig       `mapstructure:"traceroute.hops"`
	TracerouteReached    TracerouteReachedMetricConfig    `mapstructure:"traceroute.reached"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		TracerouteHopLatency: TracerouteHopLatencyMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []TracerouteHopLatencyMetricAttributeKey{TracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex, TracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress, TracerouteHopLatencyMetricAttributeKeyTracerouteTrigger, TracerouteHopLatencyMetricAttributeKeyDNSServer},
		},
		TracerouteHopStatus: TracerouteHopStatusMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []TracerouteHopStatusMetricAttributeKey{TracerouteHopStatusMetricAttributeKeyTracerouteHopIndex, TracerouteHopStatusMetricAttributeKeyTracerouteHopAddress, TracerouteHopStatusMetricAttributeKeyTracerouteTrigger, TracerouteHopStatusMetricAttributeKeyDNSServer},
		},
		TracerouteHops: TracerouteHopsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []TracerouteHopsMetricAttributeKey{TracerouteHopsMetricAttributeKeyTracerouteTrigger, TracerouteHopsMetricAttributeKeyDNSServer},
		},
		TracerouteReached: TracerouteReachedMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []TracerouteReachedMetricAttributeKey{TracerouteReachedMetricAttributeKeyTracerouteTrigger, TracerouteReachedMetricAttributeKeyDNSServer},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for networkcheck resource attributes.
type ResourceAttributesConfig struct {
	ServerAddress ResourceAttributeConfig `mapstructure:"server.address"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		ServerAddress: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for networkcheck metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
