// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					TracerouteHopLatency: TracerouteHopLatencyMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteHopLatencyMetricAttributeKey{TracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex, TracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress, TracerouteHopLatencyMetricAttributeKeyTracerouteTrigger, TracerouteHopLatencyMetricAttributeKeyDNSServer},
					},
					TracerouteHopStatus: TracerouteHopStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteHopStatusMetricAttributeKey{TracerouteHopStatusMetricAttributeKeyTracerouteHopIndex, TracerouteHopStatusMetricAttributeKeyTracerouteHopAddress, TracerouteHopStatusMetricAttributeKeyTracerouteTrigger, TracerouteHopStatusMetricAttributeKeyDNSServer},
					},
					TracerouteHops: TracerouteHopsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteHopsMetricAttributeKey{TracerouteHopsMetricAttributeKeyTracerouteTrigger, TracerouteHopsMetricAttributeKeyDNSServer},
					},
					TracerouteReached: TracerouteReachedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteReachedMetricAttributeKey{TracerouteReachedMetricAttributeKeyTracerouteTrigger, TracerouteReachedMetricAttributeKeyDNSServer},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					ServerAddress: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					TracerouteHopLatency: TracerouteHopLatencyMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteHopLatencyMetricAttributeKey{TracerouteHopLatencyMetricAttributeKeyTracerouteHopIndex, TracerouteHopLatencyMetricAttributeKeyTracerouteHopAddress, TracerouteHopLatencyMetricAttributeKeyTracerouteTrigger, TracerouteHopLatencyMetricAttributeKeyDNSServer},
					},
					TracerouteHopStatus: TracerouteHopStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteHopStatusMetricAttributeKey{TracerouteHopStatusMetricAttributeKeyTracerouteHopIndex, TracerouteHopStatusMetricAttributeKeyTracerouteHopAddress, TracerouteHopStatusMetricAttributeKeyTracerouteTrigger, TracerouteHopStatusMetricAttributeKeyDNSServer},
					},
					TracerouteHops: TracerouteHopsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteHopsMetricAttributeKey{TracerouteHopsMetricAttributeKeyTracerouteTrigger, TracerouteHopsMetricAttributeKeyDNSServer},
					},
					TracerouteReached: TracerouteReachedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []TracerouteReachedMetricAttributeKey{TracerouteReachedMetricAttributeKeyTracerouteTrigger, TracerouteReachedMetricAttributeKeyDNSServer},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					ServerAddress: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(TracerouteHopLatencyMetricConfig{}, TracerouteHopStatusMetricConfig{}, TracerouteHopsMetricConfig{}, TracerouteReachedMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestTracerouteHopLatencyMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().TracerouteHopLatency
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []TracerouteHopLatencyMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric traceroute.hop.latency doesn't have an attribute invalid, valid attributes: [traceroute.hop.index, traceroute.hop.address, traceroute.trigger, dns.server]")

	cfg = DefaultMetricsConfig().TracerouteHopLatency
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestTracerouteHopStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().TracerouteHopStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []TracerouteHopStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric traceroute.hop.status doesn't have an attribute invalid, valid attributes: [traceroute.hop.index, traceroute.hop.address, traceroute.trigger, dns.server]")

	cfg = DefaultMetricsConfig().TracerouteHopStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestTracerouteHopsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().TracerouteHops
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []TracerouteHopsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric traceroute.hops doesn't have an attribute invalid, valid attributes: [traceroute.trigger, dns.server]")

	cfg = DefaultMetricsConfig().TracerouteHops
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestTracerouteReachedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().TracerouteReached
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []TracerouteReachedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric traceroute.reached doesn't have an attribute invalid, valid attributes: [traceroute.trigger, dns.server]")

	cfg = DefaultMetricsConfig().TracerouteReached
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				ServerAddress: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				ServerAddress: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
