// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/bindplane component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bindplane")
	ScopeName = "github.com/dynatrace/dynatrace-bindplane-otel-contrib/extension/bindplaneextension"
)

const (
	ExtensionStability = component.StabilityLevelDeprecated
)
