type: googlemanagedprometheus

status:
  class: exporter
  stability:
    beta: [metrics]
  distributions: [Dynatrace-Bindplane]
  codeowners:
    active: [dynatrace/team-dynatrace-bindplane-maintainers]
