// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/sapnetweaver component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sapnetweaver")
	ScopeName = "github.com/dynatrace/dynatrace-bindplane-otel-contrib/receiver/sapnetweaverreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
