// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("pebble")
	ScopeName = "github.com/dynatrace/dynatrace-bindplane-otel-contrib/extension/pebbleextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
