# Copyright Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Drop-in replacement for the released collector image with the binary swapped
# for a local build, so an A/B run differs in nothing but the collector code.
# Build with --build-arg BIN=<path to collector_linux_<arch>> from this directory.
FROM ghcr.io/dynatrace/dynatrace-bindplane-otel-collector:1.0.0
ARG BIN=collector_bin
COPY --chown=otel:otel ${BIN} /collector/dynatrace-bindplane-otel-collector
